-- vim.g.rustaceanvim = {
--     dap = { },  -- DAP configuration
-- }

-- local format_sync_grp = vim.api.nvim_create_augroup("RustaceanFormat", {})
-- vim.api.nvim_create_autocmd("BufWritePre", {
--     buffer = bufnr,
--     pattern = "*.rs",
--     callback = function() vim.lsp.buf.format() end,
--     group = format_sync_grp,
-- })
