live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#66eeaa"
blue = "#7aa6ff"
cyan = "#22aaff"
green = "#77dd55"
magenta = "#b77ee0"
red = "#ff3355"
white = "#55ddff"
yellow = "#eed747"


[colors.normal]
black = "#ff1111"
blue = "#7aa6da"
cyan = "#22aaff"
green = "#55ff77"
magenta = "#c9a8e9"
red = "#ff1111"
white = "#ffffff"
yellow = "#eeee47"

[colors.primary]
background = "0x013931"
foreground = "0xeeeeee"

# [command]
# args = ["Hey, you should take a look on something in session: ", "zellij ls | grep current"]
# program = "notify-send"

[font]
size = 11.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Italic"
style = "Italic"

[font.normal]
family = "JetBrains Mono"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[73;5u"
key = "I"
mods = "Control|Shift"

[scrolling]
history = 10000

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.75
startup_mode = "Fullscreen"
title = "pickleshit"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
