#!/bin/sh

# cargo fmt
result=$(cargo fmt --all -- --check)
if [ $? -ne 0 ]; then
    echo "There are formatting errors"
    echo "${result}"
fi

# cargo docs
result=$(cargo test --doc --all-features)
if [ $? -ne 0 ] && [ $? -ne 101 ]; then
    echo "Errors found in the documentation"
    echo "${result}"
fi

# Run machete and clippy on each commit
if [ "$(which cargo-machete)" ]; then
    # if for some reason you have a crate that is not directly used but
    # is needed, like vendoring `native-tls` from cross
    # just add ignored to machete metadata:
    #
    # [package.metadata.cargo-machete]
    # ignored = ["prost"]
    #
    result=$(cargo machete)
    if [ $? -ne 0 ]; then
        echo "There are unused dependencies:"
        echo "${result}"
    fi
fi

if [ "$(which cargo-clippy)" ]; then
    result=$(cargo clippy  --all-features -- -D warnings)
    if [ $? -ne 0 ]; then
        echo "There there are unhandled warnings:"
        echo "${result}"
    fi
fi
