require("core.config_plugins.mini")
require("core.config_plugins.supermaven")
require("core.config_plugins.telescope")
require("core.config_plugins.log-baleia")
require("core.config_plugins.lsp")
require("core.config_plugins.noice")
require("core.config_plugins.rg")
require("core.config_plugins.snap")
require("core.config_plugins.tree")
require("core.config_plugins.themes")
require("core.config_plugins.treesitter")
require("core.config_plugins.misc")
require("core.config_plugins.multicursor")
-- require("core.config_plugins.dap")
require("core.config_plugins.ollama")
