require("core.plugin_config.rust")
require("core.plugin_config.mini")
require("core.plugin_config.telescope")
-- require("core.plugin_config.dap")
require("core.plugin_config.log-baleia")
require("core.plugin_config.tree")
require("core.plugin_config.themes")
require("core.plugin_config.treesitter")
require("core.plugin_config.snap")
require("core.plugin_config.ollama")
-- direct pluging enable
require("mason").setup()
